from __future__ import annotations

import re
from pathlib import Path

import requests
from gtts import gTTS

ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / 'src' / 'data' / 'flags.ts'
EN_AUDIO_DIR = ROOT / 'public' / 'audio' / 'names-en'
FEEDBACK_DIR = ROOT / 'public' / 'audio' / 'feedback'

MANUAL_ENGLISH_NAMES = {
    'xk': 'Kosovo'
}

ENTRY_PATTERN = re.compile(
    r"\{\s*id:\s*'(?P<id>[^']+)',\s*czechName:\s*'(?P<name>[^']+)',\s*imagePath:\s*'(?P<img>[^']+)',\s*audioPath:\s*'(?P<audio>[^']+)'\s*\},"
)


def parse_existing_entries() -> list[dict[str, str]]:
    content = DATA_FILE.read_text(encoding='utf-8')
    entries = [m.groupdict() for m in ENTRY_PATTERN.finditer(content)]
    if not entries:
        raise RuntimeError('No entries found in src/data/flags.ts')
    return entries


def fetch_english_names() -> dict[str, str]:
    response = requests.get('https://restcountries.com/v3.1/all?fields=cca2,name', timeout=60)
    response.raise_for_status()

    name_by_code: dict[str, str] = {}
    for item in response.json():
        code = item.get('cca2', '').lower()
        name = item.get('name', {}).get('common', '')
        if code and name:
            name_by_code[code] = name

    name_by_code.update(MANUAL_ENGLISH_NAMES)
    return name_by_code


def generate_english_name_audio(entries: list[dict[str, str]], english_names: dict[str, str]) -> None:
    EN_AUDIO_DIR.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []

    for entry in entries:
        code = entry['id']
        en_name = english_names.get(code)
        if not en_name:
            missing.append(code)
            continue

        target = EN_AUDIO_DIR / f'{code}.mp3'
        if target.exists() and target.stat().st_size > 1000:
            continue

        gTTS(text=en_name, lang='en').save(str(target))

    if missing:
        print('Missing English names for codes:')
        for code in missing:
            print(f'- {code}')


def generate_english_feedback() -> None:
    FEEDBACK_DIR.mkdir(parents=True, exist_ok=True)
    gTTS(text='Correct!', lang='en').save(str(FEEDBACK_DIR / 'correct-en.mp3'))
    gTTS(text='Wrong!', lang='en').save(str(FEEDBACK_DIR / 'wrong-en.mp3'))


def rewrite_data_file(entries: list[dict[str, str]], english_names: dict[str, str]) -> None:
    lines = [
        'export type FlagItem = {',
        '  id: string;',
        '  czechName: string;',
        '  englishName: string;',
        '  imagePath: string;',
        '  audioPath: string;',
        '  audioPathEn: string;',
        '};',
        '',
        '// This file is auto-generated by scripts/generate_assets.py and scripts/generate_english_assets.py',
        'export const FLAGS: FlagItem[] = ['
    ]

    for entry in entries:
        code = entry['id']
        czech_name = entry['name']
        image_path = entry['img']
        audio_path = entry['audio']
        english_name = english_names.get(code, code.upper())

        lines.append(
            "  { id: '"
            + code
            + "', czechName: '"
            + czech_name
            + "', englishName: '"
            + english_name.replace("'", "\\'")
            + "', imagePath: '"
            + image_path
            + "', audioPath: '"
            + audio_path
            + "', audioPathEn: '/audio/names-en/"
            + code
            + ".mp3' },"
        )

    lines.extend(
        [
            '];',
            '',
            'export const FEEDBACK_AUDIO = {',
            "  cs: { correct: '/audio/feedback/correct.mp3', wrong: '/audio/feedback/wrong.mp3' },",
            "  en: { correct: '/audio/feedback/correct-en.mp3', wrong: '/audio/feedback/wrong-en.mp3' }",
            '};',
            ''
        ]
    )

    DATA_FILE.write_text('\n'.join(lines), encoding='utf-8')


def main() -> None:
    entries = parse_existing_entries()
    english_names = fetch_english_names()

    generate_english_name_audio(entries, english_names)
    generate_english_feedback()
    rewrite_data_file(entries, english_names)

    print(f'Hotovo. English audio generated for {len(entries)} countries.')


if __name__ == '__main__':
    main()
